// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi5KRWOwVDb0CwhoipcrvQyjPa-kqh8MM',
    appId: '1:803486096145:web:8b2d204a2f258639be8ab0',
    messagingSenderId: '803486096145',
    projectId: 'test-task-upwork',
    authDomain: 'test-task-upwork.firebaseapp.com',
    storageBucket: 'test-task-upwork.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvIj7mZwMUEVXLfJQMdpJA_qZiaOfZ-3k',
    appId: '1:803486096145:android:76d6c17ca0088184be8ab0',
    messagingSenderId: '803486096145',
    projectId: 'test-task-upwork',
    storageBucket: 'test-task-upwork.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwhODroUPN4ZEg6qL8CMOVx2v9h14kNno',
    appId: '1:803486096145:ios:3b3075e942117c5ebe8ab0',
    messagingSenderId: '803486096145',
    projectId: 'test-task-upwork',
    storageBucket: 'test-task-upwork.appspot.com',
    iosBundleId: 'com.example.testTaskUpwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwhODroUPN4ZEg6qL8CMOVx2v9h14kNno',
    appId: '1:803486096145:ios:9365cebb2c55535abe8ab0',
    messagingSenderId: '803486096145',
    projectId: 'test-task-upwork',
    storageBucket: 'test-task-upwork.appspot.com',
    iosBundleId: 'com.example.testTaskUpwork.RunnerTests',
  );
}
